### ISSUE TITLE
lorawan trouble

### ISSUE THREAD

**Issue by italobbarros** [zterrorblade/lora_asr6505_pingpong#1]
Hi, is the code working correctly? could you tell me if it is necessary to have the file "rtc-board.c"?

**Comment by zterrorblade** [comment]
> Hi, is the code working correctly? could you tell me if it is necessary to have the file "rtc-board.c"?

Yes, it works. You should include "rtc-board.h" and use its lib libraries/asrlib/IAR/asrlib.a to compile your project unless you want to implement the timer where the timerlist bases  by yourself
